name: vediczy
description: "A new Flutter project."
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.8

  # Firebase core
  firebase_core: ^2.32.0
  # User authentication
  firebase_auth: ^4.19.4
  # Google Sign-In support
  google_sign_in: ^6.2.1
  # Firestore database
  cloud_firestore: ^4.17.4
  # Firebase Cloud Functions call
  cloud_functions: ^4.5.0
  # HTTP requests (AI API / web scraping)
  http: ^1.1.1
  # Cron / scheduling (optional Flutter-side)
  cron: ^0.3.0
  # Google Mobile Ads SDK
  google_mobile_ads: ^5.2.0
  
  # Stylish fonts for UI
  google_fonts: ^6.2.1
  
  # State Management
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Version ko 5.0.0 se 4.0.0 kiya gaya hai
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add your assets here (YEH BADLAAV KIYA GAYA HAI)
  # assets:
  #   - assets/
  
  # Add your fonts here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
