// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR8CxKyeipYpF3gRQJq-Ok0L-rUCV_ThI',
    appId: '1:591156419005:web:fed268823324819ee55ad4',
    messagingSenderId: '591156419005',
    projectId: 'r2examprep',
    authDomain: 'r2examprep.firebaseapp.com',
    storageBucket: 'r2examprep.firebasestorage.app',
    measurementId: 'G-TH2R6M6SC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobuTyRJ6lp8XugvWVgszjgynCTDyByE4',
    appId: '1:591156419005:android:7b4db51894cd47f5e55ad4',
    messagingSenderId: '591156419005',
    projectId: 'r2examprep',
    storageBucket: 'r2examprep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2alrShEvJD1qhzsJbIM3yGqdXmXKE54c',
    appId: '1:591156419005:ios:1b255e7790811c7de55ad4',
    messagingSenderId: '591156419005',
    projectId: 'r2examprep',
    storageBucket: 'r2examprep.firebasestorage.app',
    androidClientId: '591156419005-1onoukji28v456ajhq63tnj64p04i0au.apps.googleusercontent.com',
    iosClientId: '591156419005-l1ks8k6otmcusfj1u8b9m1dv0o49445u.apps.googleusercontent.com',
    iosBundleId: 'com.example.vediczy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2alrShEvJD1qhzsJbIM3yGqdXmXKE54c',
    appId: '1:591156419005:ios:1b255e7790811c7de55ad4',
    messagingSenderId: '591156419005',
    projectId: 'r2examprep',
    storageBucket: 'r2examprep.firebasestorage.app',
    androidClientId: '591156419005-1onoukji28v456ajhq63tnj64p04i0au.apps.googleusercontent.com',
    iosClientId: '591156419005-l1ks8k6otmcusfj1u8b9m1dv0o49445u.apps.googleusercontent.com',
    iosBundleId: 'com.example.vediczy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR8CxKyeipYpF3gRQJq-Ok0L-rUCV_ThI',
    appId: '1:591156419005:web:7148c5be912f75c1e55ad4',
    messagingSenderId: '591156419005',
    projectId: 'r2examprep',
    authDomain: 'r2examprep.firebaseapp.com',
    storageBucket: 'r2examprep.firebasestorage.app',
    measurementId: 'G-TXBMTKK25K',
  );
}
